import tkinter as tk
window = tk.Tk()
window.title("Geometry Methods Demo")
window.geometry("400x300")
frame_pack = tk.Frame(window, bg="lightblue")
frame_pack.pack(fill="x")
tk.Label(frame_pack, text="Using pack()", bg="lightblue").pack(pady=5)
tk.Button(frame_pack, text="Button 1").pack(side="left", padx=10, pady=5)
tk.Button(frame_pack, text="Button 2").pack(side="left", padx=10, pady=5)
frame_grid = tk.Frame(window, bg="lightgreen")
frame_grid.pack(fill="x", pady=10)
tk.Label(frame_grid, text="Using grid()", bg="lightgreen").grid(row=0, column=0, columnspan=2)
tk.Label(frame_grid, text="Name:", bg="lightgreen").grid(row=1, column=0, padx=5, pady=5)
tk.Entry(frame_grid).grid(row=1, column=1, padx=5, pady=5)
tk.Label(frame_grid, text="Age:", bg="lightgreen").grid(row=2, column=0, padx=5, pady=5)
tk.Entry(frame_grid).grid(row=2, column=1, padx=5, pady=5)
frame_place = tk.Frame(window, bg="lightyellow", height=100)
frame_place.pack(fill="both", expand=True)
tk.Label(frame_place, text="Using place()", bg="lightyellow").place(x=150, y=10)
tk.Button(frame_place, text="Click Me").place(x=160, y=40)
window.mainloo